web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - mongo
    - memcached
  volumes:
    - ./web/:/usr/src/app
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b 0.0.0.0:8000 app:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web

memcached:
  image: memcached:1.4.24
  ports:
    - "11211:11211"

mongo:
  restart: always
  build: ./mongo
  volumes:
    - /usr/local/opt/mongodb:/data/db
  ports:
    - "27027:27027"
  env_file: .env
  command: --auth
